from selenium.webdriver.support import expected_conditions as EC
import time
from selenium.webdriver import Keys, ActionChains
from selenium.webdriver.common.by import By
import logging
from src.actions.choose_bort_of_pizza import choose_bort_of_pizza_and_col
from src.actions.choose_desert import choose_desert
from selenium.webdriver.support.ui import WebDriverWait
from src.actions.push_to_card_from_slider import push_to_card_from_slider


def push_product_to_card(driver):
    wait = WebDriverWait(driver, timeout=10)
    action_chains = ActionChains(driver)
    # push_to_card_from_slider(driver, wait)
    # time.sleep(2)
    # elem = driver.find_element(By.XPATH, '//li[@data-slick-index="0"]/div/a[@title="Пицца «4 в 1»"]')
    # ActionChains(driver).move_to_element(elem).perform()
    # elem = wait.until(EC.element_to_be_clickable(elem))
    # elem.click()
    # time.sleep(5)
    # choose_bort_of_pizza_and_col(driver)
    # choose_desert(driver)
    logging.info('Добавление крайнего левого товара из открытого слайдера в корзину')
    elem = driver.find_element(By.CSS_SELECTOR, 'ul.new-prod-slide li:nth-of-type(5) a.add_to_cart_button ')
    ActionChains(driver).move_to_element(elem).perform()
    wait.until(EC.element_to_be_clickable(elem)).click()
    driver.find_element(By.XPATH, '// a[@title = "Пицца «4 в 1»"]').click()
    time.sleep(3)
    elem = driver.find_element(By.XPATH, '// select[ @ id = "board_pack"]')
    wait.until(EC.element_to_be_clickable(elem)).click()
    elem = driver.find_element(By.XPATH, '//option[contains(text(),"Сырный - 55.00 р.")]')
    wait.until(EC.element_to_be_clickable(elem)).click()
    time.sleep(4)
    elem = driver.find_element(By.XPATH, '//input[@type="number"]')
    elem.click()
    elem.clear()
    logging.info('Количество пиц с сырным бортом ввод 3 шт')
    elem.send_keys('3')
    elem = driver.find_element(By.XPATH, '//button[ @ name = "add-to-cart"]')
    elem.click()
    logging.info('Выбор борта - колбасный')
    elem = driver.find_element(By.XPATH, '//option[contains(text(),"Колбасный - 65.00 р.")]')
    wait.until(EC.element_to_be_clickable(elem)).click()
    elem = driver.find_element(By.XPATH, '//input[@type="number"]')
    elem.click()
    elem.clear()
    logging.info('Количество пиц с колбасным бортом ввод 2 шт')
    elem.send_keys('2')
    elem = driver.find_element(By.XPATH, '//button[@name = "add-to-cart"]')
    elem.click()
    logging.info('Переход в меню Десерты')
    elem = driver.find_element(By.XPATH, '//li[@id = "menu-item-389"]')
    action_chains.move_to_element(elem).perform()
    elem = driver.find_element(By.XPATH, '//li[@id = "menu-item-391"]/a')
    action_chains.move_to_element(elem).perform()
    elem.click()
    time.sleep(3)
    logging.info('Задаем диапазон цен для десертов не более 135 р')
    elem2 = driver.find_element(By.XPATH, '//span[@style="left: 100%;"]')
    action_chains = ActionChains(driver)
    action_chains.click_and_hold(elem2).move_by_offset(xoffset=-200, yoffset=0).perform()
    action_chains.release().perform()
    elem = driver.find_element(By.XPATH, '// button[text() = "Применить"]')
    elem.click()
    time.sleep(3)
    logging.info('Помещаем десерт с id 437 в корзину')
    elem = driver.find_element(By.XPATH, '//a[text()="В корзину"] [@data-product_id="437"]')
    wait.until(EC.element_to_be_clickable(elem)).click()
